version: '3.9'

services:
  postgres_container:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

  springboot_container:
    build: .

    depends_on:
      - postgres_container

    restart: always

    environment:
      DB_URL: "${DOCKER_DB_URL}"
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      BUCKET_NAME: "${BUCKET_NAME}"

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
